spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:lesson_db}
    username: ${DATASOURCE_USER:lesson_user}
    password: ${DATASOURCE_PASSWORD:secret}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    database: h2
  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    url: ${DATASOURCE_URL:jdbc:h2:mem:lesson_db}
    password: ${DATASOURCE_PASSWORD:secret}
    locations: classpath:db/migration
    user: ${DATASOURCE_USER:lesson_user}




